---
image: registry.gitlab.inria.fr/solverstack/docker/distrib

stages:
  - build
  - test
  - coverage
  - qa
  - deploy

before_script:
  - git config --global --add safe.directory $CI_PROJECT_DIR
  - git config --global --add safe.directory $CI_PROJECT_DIR/cmake_modules/morse_cmake
  - git submodule update --init --recursive

include:
  - .gitlab/common.yml
  - .gitlab/build.yml
  - .gitlab/test.yml
  - .gitlab/coverage.yml
  - .gitlab/sonarqube.yml
  - .gitlab/coverity.yml
  - .gitlab/pages.yml
  - .gitlab/release.yml
