---
.build_script_template: &build_script
  stage: build
  tags: ["docker", "large"]
  artifacts:
    name: spm_build_${VERSION}
    expire_in: 180 minutes
    untracked: true
    paths:
      - install-${VERSION}
      - build
      - spm-build-${VERSION}.log
  script:
    - .gitlab/build.sh

.build_script_template_seq: &build_script_seq
  extends:
    - .build_script_template
    - .only-branches-seq

.build_script_template_mpi: &build_script_mpi
  extends:
    - .build_script_template
    - .only-branches-mpi

build_spm_seq:
  <<: *build_script_seq
  variables:
    VERSION: seq

build_spm_mpi:
  <<: *build_script_mpi
  variables:
    VERSION: mpi

build_spm_seq_macosx:
  <<: *build_script_seq
  tags: ['macosx']
  variables:
    VERSION: seq

build_spm_mpi_macosx:
  <<: *build_script_mpi
  tags: ['macosx']
  variables:
    VERSION: mpi
