# Add OpenMPI to the environment
# export PATH=$OPENMPI_DIR/bin:$PATH
# export LD_RUN_PATH=$OPENMPI_DIR/lib:$LD_RUN_PATH
# export LD_LIBRARY_PATH=$OPENMPI_DIR/lib:$LD_LIBRARY_PATH
# export INCLUDE_PATH=$OPENMPI_DIR/include:$INCLUDE_PATH
# export PKG_CONFIG_PATH=$OPENMPI_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
